#!/bin/bash

__infi__="""
# Name: Neovim git manager
# Version: 1.3.0
# Description: Brief purpose description
# Usage: $(basename "$0") [options] [arguments]
# Options:
#   -h --help    Show this help
#   -v --version Show version
"""
set -euo pipefail

run_with_confirmation() {
    local timeout=10  # seconds to wait for input
    echo -n "Do you want to proceed? (yes/no) [Timeout in ${timeout}s]: "
    
    # Read with timeout
    if ! read -t $timeout answer; then
        echo -e "\nNo response received. Defaulting to no."
        return 1
    fi

    case "${answer,,}" in
        y|yes)
            # Your function logic here
            echo "Executing operation \" $1 \""
            return 0
            ;;
        *)
            echo "Operation \" $1 \" cancelled"
            return 1
            ;;
    esac
}
setup() {
	# Set Aliases for neovim_git
    if run_with_confirmation "alias for neovim_git"; then
        touch $HOME/.profile
        mod_script "$HOME/.profile" --add_var ng "\"neovim_git\"" --type "alias" || true
    	if [[ -f "$HOME/.zshrc" ]]; then
            mod_script $HOME/.zshrc --add_var ng "\"neovim_git\"" --type "alias" || true
        fi
        if [[ -f "$HOME/.bashrc" ]]; then
            mod_script $HOME/.bashrc --add_var ng "\"neovim_git\"" --type "alias" || true
        fi
    fi
}

help() {
	echo "$__infi__"
	echo "$(git -h)"
	exit 0
}
version() {
	echo "Version: $(grep '^# Version:' "$0" | cut -d' ' -f3)"
	echo "$(git -v)"
	exit 0
}

# Check for required tools
check_required_tools() {
	local REQUIRED_CMDS=("sh")
	for cmd in "${REQUIRED_CMDS[@]}"; do
		if ! command -v "$cmd" &>/dev/null; then
			echo "Error: $cmd is required but not installed" >&2
			exit 1
		fi
	done
}

# Only execute if the script is run directly (not sourced)
if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
	check_required_tools
fi



# Only execute if the script is run directly (not sourced)
# Main script content here
run_with_git() {
	_NEOVIM_CONFIG_DIR="${HOME}/.config/nvim"
	# If neovim config wirectory does not exist, create it
	if [ ! -d "$_NEOVIM_CONFIG_DIR" ]; then
		mkdir -p "$_NEOVIM_CONFIG_DIR"
	fi

	cd "$_NEOVIM_CONFIG_DIR"
	git "$@"
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    if [[ $# -lt 1 ]]; then
        help
    fi
	# Parse arguments
	case "$1" in
	-h | --help) help ;;
	-v | --version) version ;;
	*)
		run_with_git "$@"
		;;
	esac
	#
fi